[package]
name = "TFLMultiModeProgMap"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
ureq = "2.9.7"
